Business Rules:
1. Combine the data from both regions into a single table.

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("order_region_a(in).csv")

In [3]:
df1.head()

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764

In [4]:
df2 = pd.read_csv("order_region_b(in).csv")
df2.head(1)

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359

In [6]:
df2.shape

(44494, 6)

In [7]:
df1.shape

(44494, 6)

In [11]:
df1.columns

Index(['OrderId', 'OrderItemId', 'QuantityOrdered', 'ItemPrice',
       'PromotionDiscount', 'batch_id'],
      dtype='object')

In [12]:
df2.columns

Index(['OrderId', 'OrderItemId', 'QuantityOrdered', 'ItemPrice',
       'PromotionDiscount', 'batch_id'],
      dtype='object')

In [5]:
pd.merge(df1,df2,on='OrderId',how='inner')

,OrderId,OrderItemId_x,QuantityOrdered_x,ItemPrice_x,PromotionDiscount_x,batch_id_x,OrderItemId_y,QuantityOrdered_y,ItemPrice_y,PromotionDiscount_y,batch_id_y
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764
...,...,...,...,...,...,...,...,...,...,...,...
54873,403-9398294-9729165,2.595270e+13,1,899.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",729,2.595270e+13,1,899.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",729
54874,403-9398429-3695549,5.373600e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",151,5.373600e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",151
54875,403-9399318-8267565,7.727720e+12,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",54,7.727720e+12,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",54
54876,403-9400326-2753965,2.029820e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",1401,2.029820e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",1401
54877,403-9400753-7822741,6.437950e+12,1,629.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",461,6.437950e+12,1,629.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",461

In [13]:
pd.merge(df1,df2,on=['OrderId', 'OrderItemId', 'QuantityOrdered', 'ItemPrice','PromotionDiscount', 'batch_id'],how='inner')

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764
...,...,...,...,...,...,...
44489,403-9398294-9729165,2.595270e+13,1,899.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",729
44490,403-9398429-3695549,5.373600e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",151
44491,403-9399318-8267565,7.727720e+12,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",54
44492,403-9400326-2753965,2.029820e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",1401
44493,403-9400753-7822741,6.437950e+12,1,629.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",461

In [10]:
pd.concat([df1,df2],axis=0)

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764
...,...,...,...,...,...,...
44489,403-9398294-9729165,2.595270e+13,1,899.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",729
44490,403-9398429-3695549,5.373600e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",151
44491,403-9399318-8267565,7.727720e+12,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",54
44492,403-9400326-2753965,2.029820e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",1401
44493,403-9400753-7822741,6.437950e+12,1,629.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",461

In [14]:
df3 = pd.merge(df1,df2,on=['OrderId', 'OrderItemId', 'QuantityOrdered', 'ItemPrice','PromotionDiscount', 'batch_id'],how='inner')
df3.head()

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764

why I merged because order_a and order_b value containing same values so merged insted of combining.

Add a column total_sales which is calculated as QuantityOrdered *
ItemPrice.

In [15]:
df3['total_sales'] = df3['QuantityOrdered'] * df3['ItemPrice']
df3.head()

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,total_sales
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,949.0
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,699.0
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297,399.0
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114,499.0
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764,1699.0

In [41]:
df1['total_sales'] = df1['QuantityOrdered'] * df1['ItemPrice']   #order a
df1.head()

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,total_sales
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,949.0
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,699.0
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297,399.0
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114,499.0
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764,1699.0

In [42]:
df2['total_sales'] = df2['QuantityOrdered'] * df2['ItemPrice']   #order b
df2.head()

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,total_sales
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,949.0
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,699.0
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297,399.0
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114,499.0
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764,1699.0

Add a column region to identify the region of the sales record (A or B).

In [19]:
pd.concat([df1,df2],axis=0)

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764
...,...,...,...,...,...,...
44489,403-9398294-9729165,2.595270e+13,1,899.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",729
44490,403-9398429-3695549,5.373600e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",151
44491,403-9399318-8267565,7.727720e+12,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",54
44492,403-9400326-2753965,2.029820e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",1401
44493,403-9400753-7822741,6.437950e+12,1,629.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",461

In [27]:
pd.concat([df1,df2],axis=0)

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764
...,...,...,...,...,...,...
44489,403-9398294-9729165,2.595270e+13,1,899.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",729
44490,403-9398429-3695549,5.373600e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",151
44491,403-9399318-8267565,7.727720e+12,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",54
44492,403-9400326-2753965,2.029820e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",1401
44493,403-9400753-7822741,6.437950e+12,1,629.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",461

Ensure that there are no duplicate entries based on OrderId.

In [ ]:
df1.duplicated('OrderId').sum() #order a

np.int64(3387)

In [ ]:
df2.duplicated('OrderId').sum() #order b

np.int64(3387)

In [ ]:
df3.duplicated('OrderId').sum() #merge a and b

np.int64(3387)

In [34]:
df1.drop_duplicates('OrderId',inplace=True)

In [35]:
df1.duplicated('OrderId').sum()

np.int64(0)

In [36]:
df1.shape

(41107, 6)

In [37]:
df2.drop_duplicates('OrderId',inplace=True)

In [38]:
df2.duplicated('OrderId').sum()

np.int64(0)

In [39]:
df3.drop_duplicates('OrderId',inplace=True)

In [40]:
df3.duplicated('OrderId').sum()

np.int64(0)

Add a new column net_sale, calculated as total_sales - PromotionDiscount.

In [44]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41107 entries, 0 to 44493
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   OrderId            41107 non-null  object
 1   OrderItemId        41107 non-null  float64
 2   QuantityOrdered    41107 non-null  int64
 3   ItemPrice          41107 non-null  float64
 4   PromotionDiscount  41107 non-null  object
 5   batch_id           41107 non-null  int64
 6   total_sales        41107 non-null  float64
dtypes: float64(3), int64(2), object(2)
memory usage: 2.5+ MB

In [45]:
df3.head(2)

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,total_sales
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,949.0
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,699.0

In [56]:
df3['PromotionDiscount'].value_counts()

PromotionDiscount
{ "CurrencyCode": "INR", "Amount": "10.1"}    20559
{ "CurrencyCode": "INR", "Amount": "10"}      20548
Name: count, dtype: int64

In [57]:
df3['pd'] = df3['PromotionDiscount'].str[36:38].astype('float64')
df3.head(2)

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,total_sales,pd
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,949.0,10.0
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,699.0,10.0

In [58]:
df3['net_sale'] = df3['total_sales'] - df3['pd']
df3.head(2)

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,total_sales,pd,net_sale
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,949.0,10.0,939.0
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,699.0,10.0,689.0

In [ ]:
df1['PromotionDiscount'].value_counts() #order a

PromotionDiscount
{ "CurrencyCode": "INR", "Amount": "10.1"}    20559
{ "CurrencyCode": "INR", "Amount": "10"}      20548
Name: count, dtype: int64

In [61]:
df1['pd'] = df1['PromotionDiscount'].str[36:38].astype('float64')
df1.head(2)

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,total_sales,pd
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,949.0,10.0
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,699.0,10.0

In [62]:
df1['net_sale'] = df1['total_sales'] - df1['pd']
df1.head(2)

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,total_sales,pd,net_sale
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,949.0,10.0,939.0
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,699.0,10.0,689.0

In [63]:
df2['PromotionDiscount'].value_counts() #order b

PromotionDiscount
{ "CurrencyCode": "INR", "Amount": "10.1"}    20559
{ "CurrencyCode": "INR", "Amount": "10"}      20548
Name: count, dtype: int64

In [64]:
df2['pd'] = df2['PromotionDiscount'].str[36:38].astype('float64')
df2.head(2)

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,total_sales,pd
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,949.0,10.0
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,699.0,10.0

In [65]:
df2['net_sale'] = df2['total_sales'] - df2['pd']
df2.head(2)

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,total_sales,pd,net_sale
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,949.0,10.0,939.0
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,699.0,10.0,689.0

Exclude orders where the total sales amount is negative or zero after applying
discounts.

In [78]:
# after applying discounts means it is net_sale
df3[df3['net_sale']<=0]['net_sale'].shape

(55,)

In [81]:
df3[df3['net_sale']>0]

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,total_sales,pd,net_sale
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,949.0,10.0,939.0
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,699.0,10.0,689.0
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297,399.0,10.0,389.0
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114,499.0,10.0,489.0
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764,1699.0,10.0,1689.0
...,...,...,...,...,...,...,...,...,...
44489,403-9398294-9729165,2.595270e+13,1,899.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",729,899.0,10.0,889.0
44490,403-9398429-3695549,5.373600e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",151,499.0,10.0,489.0
44491,403-9399318-8267565,7.727720e+12,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",54,499.0,10.0,489.0
44492,403-9400326-2753965,2.029820e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",1401,499.0,10.0,489.0
44493,403-9400753-7822741,6.437950e+12,1,629.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",461,629.0,10.0,619.0

In [82]:
df3 = df3[df3['net_sale']>0]

In [84]:
df3.head(1)

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,total_sales,pd,net_sale
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,949.0,10.0,939.0

In [83]:
df3.shape

(41052, 9)

In [85]:
# after applying discounts means it is net_sale   order a
df1[df1['net_sale']<=0]['net_sale'].shape

(55,)

In [86]:
df1 = df1[df1['net_sale']>0]

In [89]:
df1.shape

(41052, 9)

In [87]:
# after applying discounts means it is net_sale   order b
df2[df2['net_sale']<=0]['net_sale'].shape

(55,)

In [88]:
df2 = df2[df2['net_sale']>0]

In [90]:
df2.shape

(41052, 9)

Ensure data is cleaned, and all business rules are applied (including removal of
duplicates and filtering based on net_sales).

In [91]:
df3.isnull().sum()

OrderId              0
OrderItemId          0
QuantityOrdered      0
ItemPrice            0
PromotionDiscount    0
batch_id             0
total_sales          0
pd                   0
net_sale             0
dtype: int64

In [ ]:
# Exclude orders where the total sales amount is negative or zero after applying discounts.
# Filtering is done on based of net_sales

3. Load Data:
a. Create a table sales_data.

In [92]:
df1.shape

(41052, 9)

In [93]:
df2.shape

(41052, 9)

In [94]:
df3.shape

(41052, 9)

In [ ]:
pd.concat([df1,df2],axis=0)

,OrderId,OrderItemId,QuantityOrdered,ItemPrice,PromotionDiscount,batch_id,total_sales,pd,net_sale
0,171-0001135-1657958,1.116890e+13,1,949.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",359,949.0,10.0,939.0
1,171-0001497-9165123,1.976030e+13,1,699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",1135,699.0,10.0,689.0
2,171-0002127-1363507,5.949760e+12,1,399.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",297,399.0,10.0,389.0
3,171-0002370-0601169,5.757190e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",114,499.0,10.0,489.0
4,171-0004526-2028348,3.385130e+13,1,1699.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",764,1699.0,10.0,1689.0
...,...,...,...,...,...,...,...,...,...
44489,403-9398294-9729165,2.595270e+13,1,899.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",729,899.0,10.0,889.0
44490,403-9398429-3695549,5.373600e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",151,499.0,10.0,489.0
44491,403-9399318-8267565,7.727720e+12,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",54,499.0,10.0,489.0
44492,403-9400326-2753965,2.029820e+13,1,499.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10""}",1401,499.0,10.0,489.0
44493,403-9400753-7822741,6.437950e+12,1,629.0,"{ ""CurrencyCode"": ""INR"", ""Amount"": ""10.1""}",461,629.0,10.0,619.0

In [98]:
df3.to_csv("sales_data.csv")

In [99]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41052 entries, 0 to 44493
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   OrderId            41052 non-null  object
 1   OrderItemId        41052 non-null  float64
 2   QuantityOrdered    41052 non-null  int64
 3   ItemPrice          41052 non-null  float64
 4   PromotionDiscount  41052 non-null  object
 5   batch_id           41052 non-null  int64
 6   total_sales        41052 non-null  float64
 7   pd                 41052 non-null  float64
 8   net_sale           41052 non-null  float64
dtypes: float64(5), int64(2), object(2)
memory usage: 3.1+ MB